spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vitacheck_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: dkxl5743

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
